version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes

permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - directory
      - file

hooks:
  AfterInstall:
    - location: stop.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: start.sh
      timeout: 60
      runas: ec2-user

  ValidateService:
    - location: health.sh
      timeout: 60
      runas: ec2-user
