version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/luck-kids-server
    overwrite: yes

permissions:
  - object: /home/ec2-user/luck-kids-server
    pattern: "**"
    owner: ec2-user
    group: ec2-user
  - object: /home/ec2-user/luck-kids-server/deploy.sh
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStart:
    - location: /home/ec2-user/luck-kids-server/deploy.sh
      timeout: 60
      runas: ec2-user