version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/app
    overwrite: yes

permissions:
  - object: /home/ec2-user/app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755

hooks:
  ApplicationStart:
    - location: /home/ec2-user/app/deploy.sh
      timeout: 60
      runas: ec2-user