spring:
  profiles:
    default: local

  mail:
    # Google smtp server 사용
    host: smtp.gmail.com
    port: 587
    username: nav104888@gmail.com
    password: kzmearkdbqtjjbxt
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true

jwt:
  secret-key: a964233191a19f309ad49de2825616e6faa2b1e147d7e4246d289a49fe9c970fcd974b2d06dfbd657e3faa03f66986c41456f6986140be7d8a547ab8298211c7

---
spring:
  config:
    activate:
      on-profile: local

  jpa:
    open-in-view: false
    show-sql: true
    datasource: mysql
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 100
        jdbc:
          exception-handling: ignore
    mvc:
      pathmatch:
        matching-strategy: ANT_PATH_MATCHER

  decorator:
    datasource:
      p6spy:
        enable-logging: true

---
spring:
  config:
    activate:
      on-profile: test

  datasource:
    url: jdbc:h2:mem:~/luckKids;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  sql:
    init:
      mode: never
