### 홈/캘린더 조회

GET localhost:8080/api/v1/home/calendar
Content-Type: application/json
Authorization: Bearer JWT_TOKEN

### 홈/캘린더_세부 조회

GET localhost:8080/api/v1/home/calendar/2023-11-11
Content-Type: application/json
Authorization: Bearer JWT_TOKEN

### 홈/알림 조회

GET localhost:8080/api/v1/alertHistories?page=1&size=12
Content-Type: application/json
Authorization: Bearer JWT_TOKEN

### 홈/알림 조회

GET localhost:8080/api/v1/home/main
Content-Type: application/json
Authorization: Bearer JWT_TOKEN