### 신규 미션 등록
POST localhost:8080/api/v1/missions/new
Content-Type: application/json
Authorization: Bearer JWT_TOKEN

{
  "missionType": "HEALTH",
  "missionDescription": "운동하기",
  "alertStatus": "CHECKED",
  "alertTime": "18:30"
}

### 미션 수정
PATCH localhost:8080/api/v1/missions/98
Content-Type: application/json
Authorization: Bearer JWT_TOKEN

{
  "missionType": "SELF_DEVELOPMENT",
  "missionActive": "FALSE",
  "missionDescription": "책읽기",
  "alertTime": "10:30"
}

### 미션 조회

GET localhost:8080/api/v1/missions
Content-Type: application/json
Authorization: Bearer JWT_TOKEN

### 미션 삭제
DELETE localhost:8080/api/v1/missions/99
Content-Type: application/json
Authorization: Bearer JWT_TOKEN